version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: churn-backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build: 
      context: ui
    container_name: churn-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/app
      - /app/node_modules
      - /app/.next
    restart: always